name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/papers/chilecon/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs/papers/chilecon
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/papers/chilecon/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build presentation
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/papers/chilecon/dist
          destination_dir: chilecon
          keep_files: true

